name: torchgeo
channels:
  - conda-forge
dependencies:
  - cudatoolkit
  - einops
  - fiona>=1.5
  - h5py
  - numpy
  - pip
  - pycocotools
  - pyproj>=2.2.0
  - python>=3.6
  - pytorch-gpu>=1.7
  - rarfile>=3
  - rasterio>=1.0.16
  - shapely>=1.3.0
  - torchvision>=0.3
  - pip:
    - black>=21.4b0
    - flake8>=3.8
    - ipywidgets>=7
    - isort[colors]>=5.8
    - jupyterlab
    - mypy>=0.900
    - nbmake>=0.1
    - nbsphinx>=0.8.5
    - omegaconf>=2.1
    - opencv-python
    - pillow>=2.9
    - pydocstyle[toml]>=6.1
    - pytest>=6
    - pytest-cov>=2.4
    - pytorch-lightning>=1.3
    - git+https://github.com/pytorch/pytorch_sphinx_theme
    - radiant-mlhub>=0.2.1
    - rtree>=0.5
    - scikit-learn>=0.18
    - scipy>=1.6.0
    - segmentation-models-pytorch>=0.2
    - setuptools>=30.4
    - sphinx>=3
    - torchmetrics
