name: torchgeo
channels:
  - pytorch  # for pytorch and torchvision.
  - conda-forge
dependencies:
  - einops>=0.3
  - fiona>=1.8.19
  - h5py>=3
  - matplotlib>=3.3.3
  - numpy>=1.19.3
  - pip
  - pycocotools>=2.0.4
  - pyproj>=3
  - python>=3.9
  - pytorch>=1.12
  - pyvista>=0.29
  - rarfile>=4
  - rasterio>=1.2
  - shapely>=1.7.1
  - torchvision>=0.13
  - pip:
    - black[jupyter]>=21.8
    - flake8>=3.8
    - hydra-core>=1
    - ipywidgets>=7
    - isort[colors]>=5.8
    - kornia>=0.6.9
    - laspy>=2
    - lightly>=1.4.4
    - lightning>=1.8
    - mypy>=0.900
    - nbmake>=1.3.3
    - nbsphinx>=0.8.5
    - omegaconf>=2.0.1
    - opencv-python>=4.4.0.46
    - pandas>=1.1.3
    - pillow>=8
    - pydocstyle[toml]>=6.1
    - pytest>=6.2
    - pytest-cov>=2.4
    - git+https://github.com/pytorch/pytorch_sphinx_theme
    - pyupgrade>=2.8
    - radiant-mlhub>=0.3
    - rtree>=1
    - scikit-image>=0.18
    - scipy>=1.6.2
    - segmentation-models-pytorch>=0.2
    - setuptools>=42
    - sphinx>=4,<6
    - tensorboard>=2.9.1
    - timm>=0.4.12
    - torchmetrics>=0.10
    - zipfile-deflate64>=0.2
