name: torchgeo
channels:
  - pytorch  # for pytorch and torchvision.
  - conda-forge
  - esri  # for pycocotools. Remove when https://github.com/conda-forge/pycocotools-feedstock/issues/16 is solved
  - open3d-admin  # for open3d
dependencies:
  - einops
  - fiona>=1.5
  - h5py
  - numpy
  - open3d>=0.11.2
  - pip
  - protobuf<4
  - pycocotools
  - pyproj>=2.2
  - python>=3.7
  - pytorch>=1.7
  - rarfile>=3
  - rasterio>=1.0.16
  - shapely>=1.3
  - torchvision>=0.10
  - pip:
    - black>=21.4b0
    - flake8>=3.8
    - ipywidgets>=7
    - isort[colors]>=5.8
    - jupyterlab
    - kornia>=0.6.4
    - laspy>=2.0.0
    - mypy>=0.900
    - nbmake>=0.1
    - nbsphinx>=0.8.5
    - omegaconf>=2.1
    - opencv-python
    - pandas>=0.23.2
    - pillow>=2.9
    - pydocstyle[toml]>=6.1
    - pytest>=6
    - pytest-cov>=2.4
    - pytorch-lightning>=1.3
    - git+https://github.com/pytorch/pytorch_sphinx_theme
    - radiant-mlhub>=0.2.1
    - rtree>=0.5
    - scikit-learn>=0.18
    - scipy>=0.9
    - segmentation-models-pytorch>=0.2
    - setuptools>=42
    - sphinx>=4
    - timm>=0.2.1
    - torchmetrics>=0.7
    - zipfile-deflate64>=0.2
