name: coverage
on:
  workflow_run:
    workflows: [tests]
    types: [completed]
jobs:
  codecov:
    name: codecov
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4.1.1
      with:
        github-token: ${{ github.token }}
        run-id: ${{ github.event.workflow_run.id }}
    - name: Parse artifacts
      id: parse_artifacts
      run: |
        unzip pr_number.zip
        unzip commit_sha.zip
        echo "pr_number=$(<pr_number.txt)" >> "$GITHUB_OUTPUT"
        echo "commit_sha=$(<commit_sha.txt)" >> "$GITHUB_OUTPUT"
    - name: Clone repo
      uses: actions/checkout@v4.1.1
      with:
        ref: ${{ steps.parse_artifacts.outputs.commit_sha || '' }}
    - name: Report coverage
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        override_commit: ${{ steps.parse_artifacts.outputs.commit_sha || '' }}
        override_pr: ${{ steps.parse_artifacts.outputs.pr_number || '' }}

